version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
  
  frontend:
    build: ./frontend
    ports:
      # Moved to 4000 to avoid Grafana (3000) and Jenkins (8080)
      - "4000:80"
    depends_on:
      - backend